---
output: 
  md_document:
    variant: markdown_github
---

## Trabajo en equipo para la asignatura "Big Data"

<!-- El párrafo de abajo has de dejarlo tal cual. NO HAS DE CAMBIAR NADA!!-->

Repo utilizado para elaborar el trabajo en equipo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2021-2022. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-21-22-web/>.


<!-- En la linea de abajo HAS de SUSTITUIR "perezp44" por tu usuario de Github-->
La versión final del trabajo puede visualizarse en: <https://joorge0603.github.io/trabajo_BigData_equipo/>. 


<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, tenéis que poner el título del trabajo y el nombre de los componentes del equipo-->

El título del trabajo es "La piratería desde 1993 a nuestros días". Los autores de trabajo son Teodoro D'Agostino, Jorge González y Aurora Lloret.

Cuando oimos hablar de piratas es común pensar en famosos personajes de ficción mirando a través de monóculos y gritando: "Aaargh el barco". No obstante, la piratería es un serio problema que aun en nuestros días sigue causando graves problemas a marineros y mercantes. La evidencia empírica nos muestra que existen dos principales zonas geográficas donde estos ataques se concentran. En este trabajo, trataremos de dar una respuesta al por qué los ataques piratas son más frecuentes en unas zonas y menos en otras. Además, realizaremos una pequeña exploración a una serie de indicadores con el fin de entender las distintas características de los países.



<!-- Finalmente, acuérdate que cuando hayas hecho los cambios y hayas dejado este archivo como hayáis decidido, TENEIS que knittearlo para que los cambio se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github-->

